import type { Listing, PaymentRecord, UserProfile } from "./types";

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    slug: "istanbul-kadikoy-santiye-sefi-araniyor",
    listingType: "employer",
    title: "İstanbul / Kadıköy - Şantiye Şefi Aranıyor",
    city: "İstanbul",
    district: "Kadıköy",
    position: "Şantiye Şefi",
    projectType: "Konut",
    workType: "full_time",
    experienceYears: 5,
    salaryText: "Maaş yüz yüze görüşülecek",
    description:
      "Kadıköy bölgesindeki konut projemiz için saha koordinasyonu güçlü, ekip yönetimi deneyimi olan şantiye şefi arıyoruz.",
    contactName: "Ahmet Yılmaz",
    contactPhone: "05xx xxx xx xx",
    whatsappEnabled: true,
    companyName: "Yılmaz Yapı",
    isFeatured: true,
    isUrgent: true,
    status: "active",
    viewCount: 184,
    contactClickCount: 22,
    createdAt: "2026-05-10T09:00:00.000Z",
    updatedAt: "2026-05-10T09:00:00.000Z",
    expiresAt: "2026-06-10T09:00:00.000Z",
  },
  {
    id: "listing-2",
    slug: "ankara-cankaya-insaat-muhendisi-araniyor",
    listingType: "employer",
    title: "Ankara / Çankaya - İnşaat Mühendisi Aranıyor",
    city: "Ankara",
    district: "Çankaya",
    position: "İnşaat Mühendisi",
    projectType: "Ofis",
    workType: "full_time",
    experienceYears: 3,
    salaryText: "Deneyime göre değerlendirilecek",
    description:
      "Ofis ve ticari alan projemizde metraj, hakediş ve saha takibi yapabilecek inşaat mühendisi arıyoruz.",
    contactName: "Elif Demir",
    contactPhone: "05xx xxx xx xx",
    whatsappEnabled: false,
    companyName: "Demir İnşaat",
    isFeatured: true,
    isUrgent: false,
    status: "active",
    viewCount: 96,
    contactClickCount: 11,
    createdAt: "2026-05-11T11:30:00.000Z",
    updatedAt: "2026-05-11T11:30:00.000Z",
  },
  {
    id: "listing-3",
    slug: "istanbul-avrupa-yakasi-santiye-sefligi-icin-uygunum",
    listingType: "worker",
    title: "İstanbul Avrupa Yakası - Şantiye Şefliği İçin Uygunum",
    city: "İstanbul",
    district: "Avrupa Yakası",
    position: "Şantiye Şefi",
    projectType: "Konut / Ticari",
    workType: "full_time",
    experienceYears: 8,
    salaryText: "Proje koşullarına göre görüşülür",
    description:
      "Konut, villa ve ticari projelerde kaba/ince işler dahil saha yönetimi tecrübem var. İstanbul Avrupa Yakası projeleriyle ilgileniyorum.",
    contactName: "Murat Kaya",
    contactPhone: "05xx xxx xx xx",
    whatsappEnabled: true,
    isFeatured: false,
    isUrgent: false,
    status: "active",
    viewCount: 143,
    contactClickCount: 18,
    createdAt: "2026-05-12T14:20:00.000Z",
    updatedAt: "2026-05-12T14:20:00.000Z",
  },
  {
    id: "listing-4",
    slug: "izmir-bornova-mimar-is-ariyorum",
    listingType: "worker",
    title: "İzmir / Bornova - Mimar İş Arıyorum",
    city: "İzmir",
    district: "Bornova",
    position: "Mimar",
    projectType: "Konut / İç mekan",
    workType: "project_based",
    experienceYears: 4,
    description:
      "Ruhsat, uygulama projesi ve saha koordinasyonu alanlarında proje bazlı veya tam zamanlı çalışma için uygunum.",
    contactName: "Zeynep Arslan",
    contactPhone: "05xx xxx xx xx",
    whatsappEnabled: true,
    isFeatured: false,
    isUrgent: false,
    status: "active",
    viewCount: 71,
    contactClickCount: 7,
    createdAt: "2026-05-13T08:15:00.000Z",
    updatedAt: "2026-05-13T08:15:00.000Z",
  },
  {
    id: "listing-5",
    slug: "bursa-nilufer-saha-formeni-araniyor",
    listingType: "employer",
    title: "Bursa / Nilüfer - Saha Formeni Aranıyor",
    city: "Bursa",
    district: "Nilüfer",
    position: "Saha Formeni",
    projectType: "Endüstriyel tesis",
    workType: "full_time",
    experienceYears: 6,
    salaryText: "Yol + yemek + maaş",
    description:
      "Endüstriyel tesis projemizde taşeron koordinasyonu ve günlük saha planlaması yapabilecek formen arıyoruz.",
    contactName: "Kemal Öztürk",
    contactPhone: "05xx xxx xx xx",
    whatsappEnabled: true,
    companyName: "Öztürk Proje",
    isFeatured: false,
    isUrgent: true,
    status: "pending_payment",
    viewCount: 38,
    contactClickCount: 2,
    createdAt: "2026-05-14T10:00:00.000Z",
    updatedAt: "2026-05-14T10:00:00.000Z",
  },
  {
    id: "listing-6",
    slug: "antalya-muratpasa-elektrik-teknikeri-araniyor",
    listingType: "employer",
    title: "Antalya / Muratpaşa - Elektrik Teknikeri Aranıyor",
    city: "Antalya",
    district: "Muratpaşa",
    position: "Elektrik Teknikeri",
    projectType: "Otel",
    workType: "temporary",
    experienceYears: 2,
    description:
      "Otel renovasyon projesinde geçici süreli çalışacak, zayıf akım ve saha uygulama takibi yapabilecek elektrik teknikeri arıyoruz.",
    contactName: "Selin Koç",
    contactPhone: "05xx xxx xx xx",
    whatsappEnabled: false,
    companyName: "Akdeniz Yapı",
    isFeatured: false,
    isUrgent: false,
    status: "active",
    viewCount: 62,
    contactClickCount: 5,
    createdAt: "2026-05-15T12:45:00.000Z",
    updatedAt: "2026-05-15T12:45:00.000Z",
  },
];

export const mockUsers: UserProfile[] = [
  {
    id: "user-1",
    role: "admin",
    displayName: "Admin Kullanıcı",
    email: "admin@santiyeilan.com",
    createdAt: "2026-05-01T09:00:00.000Z",
  },
  {
    id: "user-2",
    role: "employer",
    displayName: "Yılmaz Yapı",
    email: "info@yilmazyapi.com",
    phone: "05xx xxx xx xx",
    city: "İstanbul",
    createdAt: "2026-05-04T09:00:00.000Z",
  },
  {
    id: "user-3",
    role: "worker",
    displayName: "Murat Kaya",
    email: "murat@example.com",
    phone: "05xx xxx xx xx",
    city: "İstanbul",
    createdAt: "2026-05-06T09:00:00.000Z",
  },
];

export const mockPayments: PaymentRecord[] = [
  {
    id: "payment-1",
    userId: "user-2",
    listingId: "listing-1",
    provider: "manual",
    packageType: "featured",
    amount: 499,
    currency: "TRY",
    status: "success",
    createdAt: "2026-05-10T10:00:00.000Z",
  },
  {
    id: "payment-2",
    userId: "user-2",
    listingId: "listing-1",
    provider: "manual",
    packageType: "urgent",
    amount: 299,
    currency: "TRY",
    status: "success",
    createdAt: "2026-05-10T10:05:00.000Z",
  },
  {
    id: "payment-3",
    userId: "user-3",
    listingId: "listing-3",
    provider: "iyzico",
    packageType: "featured",
    amount: 499,
    currency: "TRY",
    status: "pending",
    createdAt: "2026-05-12T15:00:00.000Z",
  },
];
